services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./django_bot:/app/django_bot
    depends_on:
      - db
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8080:8080"
    volumes:
      - ./streamlit_src:/app/streamlit_src
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: celery -A django_bot worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - ./django_bot:/app/django_bot
    env_file:
      - .env
    working_dir: /app/django_bot
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/django_bot

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: celery -A django_bot beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - django
    volumes:
      - ./django_bot:/app/django_bot
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    working_dir: /app/django_bot
    env_file:
      - .env

volumes:
  postgres_data: