FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc && \
    apt-get clean

WORKDIR /app

COPY requirements/streamlit.txt /app/
RUN pip install --no-cache-dir -r streamlit.txt

COPY ./streamlit_src /app/streamlit_src

EXPOSE 8080

CMD ["streamlit", "run", "streamlit_src/main.py", "--server.port", "8080"]